### ISSUE TITLE
adhoc sign on gihub actions

### ISSUE THREAD

**Issue by retyui** [nitro-build/github-action-nitro-ios#1]
I see the next warn. every time when try to build iOS with adhoc sign:

```
Unexpected input(s) 'certificate-base64', 'certificate-passphrase', 'codesigning-identity', 'provisioning-profiles-base64', 'provisioning-profile-specifier', valid inputs are ['name', 'path', 'if-no-files-found', 'retention-days']
```

I use `nitro-build/github-action-nitro-ios@v1` from docs: https://docs.nitro.build/docs/advanced-scenarios#ios-adhoc-signing

**Comment by jpgarcia** [comment]
Hi @retyui thanks for reporting this! 

Could you provide your `.yml` configuration so we can reproduce the issue? 

> No need to include sensitive info, just redact those values as `******`

**Comment by retyui** [comment]
that my mistake, I put options in incorrect actions   

```
      - uses: nitro-build/github-action-nitro-ios@v1
        id: nitro
      - uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.nitro.outputs.nitro-output-dir }}
          certificate-base64: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_BASE64 }}
          certificate-passphrase: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_PASSWORD }}
          codesigning-identity: Davyd Narbutovich (ZXB65YLHFM)
          provisioning-profiles-base64: ${{ secrets.IOS_ADHOC_PROVISIONING_PROFILE_BASE64 }}
          provisioning-profile-specifier: github actions
          pre-build-command: npx envinfo
          pre-install-command: npx envinfo
          post-build-command: npx envinfo
```
